[engine]
cgroup_manager = "cgroupfs"
events_logger = "file"
helper_binaries_dir = [
    "/snap/podman/current/usr/bin",
    "/snap/podman/current/usr/libexec/podman"
]
conmon_path = [
    "/snap/podman/current/usr/bin/conmon",
    "/snap/podman/current/usr/libexec/podman/conmon"
]
runtime = "crun"

[engine.runtimes]
crun = [
    "/snap/podman/current/usr/bin/crun",
    "/snap/podman/current/usr/libexec/podman/crun",
]

[network]
network_backend = "netavark"
